### ISSUE TITLE
Make "accounts" section work

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/testbed-bare-metal-host#3]
The `accounts` section of the config file doesn't do anything.

```
  # SSH from the outside
  ssh:
    # Port to listen on in addition to 22
    port: 22022
    accounts:
      - login: "foo"
        gecos: "Fred Foo"
        keys:
          - "ssh-ed25519 ... foo@bar"
        sudo: true
```
